# Generated by Django 3.2.6 on 2021-08-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pronouns',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
