# Generated by Django 3.2.6 on 2021-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0002_entry_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
